name: Terraform CI/CD

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform PLAN
      run: |
        cd infra

        echo "Initializing Terraform"
        terraform init
        
        echo "Running terraform fmt"
        terraform fmt -check

        echo "Running terraform validate"
        terraform validate

        echo "Creating Terraform plan"
        terraform plan -out=tfplan

    - name: Upload plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-artifact
        path: infra/tfplan

    - name: Download plan artifact
      uses: actions/download-artifact@v4
      with:
        name: tfplan-artifact
        path: planfile

    - name: Terraform APPLY (script)
      run: |
        cd infra
        
        echo "Applying Terraform plan"
        terraform init

        terraform apply -auto-approve ../planfile/tfplan
