name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    runs-on: self-hosted
    
    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform PLAN
      run: |
        cd infra

        echo "Environment chosen: ${ENV}"

        echo "Initializing Terraform"
        terraform init
        
        echo "Running terraform fmt"
        terraform fmt -check

        echo "Running terraform validate"
        terraform validate

        echo "Creating Terraform plan"
        terraform plan -var-file="${ENV}.tfvars" -out=tfplan

    - name: Upload plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-artifact
        path: infra/tfplan

    - name: Download plan artifact
      uses: actions/download-artifact@v4
      with:
        name: tfplan-artifact
        path: planfile

    - name: Terraform APPLY (script)
      run: |
        cd infra
        
        echo "Applying Terraform plan for ENV=${ENV}"
        terraform init
        terraform apply -auto-approve ../planfile/tfplan
